### ISSUE TITLE
Awesome Flutter

### ISSUE THREAD

**Issue by Solido** [angel-example/flutter#1]
Added to https://github.com/Solido/awesome-flutter#frameworks
Thanks Tobe

**Comment by thosakwe** [comment]
Whoo! Thanks. Going to upload the Flutter client code later.

**Comment by Solido** [comment]
Ah that's really great, tell me when it's done. Angel deserve a lot a public views. Thanks !

**Comment by thosakwe** [comment]
Thanks. Trying to grow the framework's popularity this year. :thumbsup:
